version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka1:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG_DIRS: /mnt/data/kafka-logs
    volumes:
      - /mnt/data/kafka1:/mnt/data/kafka-logs
    networks:
      - kafka-network

  kafka2:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_LOG_DIRS: /mnt/data/kafka-logs
    volumes:
      - /mnt/data/kafka2:/mnt/data/kafka-logs
    networks:
      - kafka-network

  kafka3:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_LOG_DIRS: /mnt/data/kafka-logs
    volumes:
      - /mnt/data/kafka3:/mnt/data/kafka-logs
    networks:
      - kafka-network

  producer:
    image: python:3.8-slim
    deploy:
      replicas: 1
    networks:
      - kafka-network
    volumes:
      - ./app:/app
    working_dir: /app
    command: python produce_events.py
    depends_on:
      - kafka1
      - kafka2
      - kafka3

volumes:
  /mnt/data/kafka1:
  /mnt/data/kafka2:
  /mnt/data/kafka3:

networks:
  kafka-network:
    driver: overlay
