version: '3.7'

services:
  minio1:
    image: minio/minio:latest
    container_name: minio1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server http://minio1/data http://minio2/data http://minio3/data
    volumes:
      - /mnt/data:/mnt/data
    ports:
      - "9001:9000"
    networks:
      - minio-network

  minio2:
    image: minio/minio:latest
    container_name: minio2
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server http://minio1/data http://minio2/data http://minio3/data
    volumes:
      - /mnt/data:/mnt/data
    networks:
      - minio-network

  minio3:
    image: minio/minio:latest
    container_name: minio3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server http://minio1/data http://minio2/data http://minio3/data
    volumes:
      - /mnt/data:/mnt/data
    networks:
      - minio-network

networks:
  minio-network:
    driver: bridge
